---
# This playbook deploys a simple standalone Tomcat 7 server.  and configure the mySql

- hosts: tomcat-servers
  remote_user: root
  become: yes
  become_method: sudo

  roles:
    - selinux
    - tomcat
    - mysql